name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - run: yarn
            - run: yarn note-api test --ci
            - run: yarn note-api build
            - run: yarn client test --ci
            - run: yarn server test --ci
